name: Run Tests

on:
  push:
    branches: [ sandra ]
  pull_request:
    branches: [ sandra ]

jobs: 
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests (backend)
        working-directory: ./backend
        run: npm test
